version: '3.9'

services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - /app/node_modules
    container_name: nest-app
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
    depends_on:
      - db
#  next-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - .:/app/
#      - /app/node_modules
#    container_name: next-app
#    ports:
#      - 3000:3000
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}